### ISSUE TITLE
[style] 参考 UI

### ISSUE THREAD

**Issue by Hunlongyu** [terasum/medict#102]
![youdao_dictionary](https://user-images.githubusercontent.com/15273630/127102168-357652bd-791f-4028-8cf0-de0964499c60.png)
![artboard](https://user-images.githubusercontent.com/15273630/127102172-92f44e45-eff2-471d-ad33-ad3967cb9ab7.png)
![dictionary](https://user-images.githubusercontent.com/15273630/127102173-5e9af561-29fc-45b7-9489-156aca31f99e.png)
![dribbble_shot](https://user-images.githubusercontent.com/15273630/127102174-edc6211c-82bf-482c-81ef-e7582ac75fdd.png)

**Comment by shawkynasr** [comment]
其他的UI
https://dribbble.com/tags/online_dictionary

**Comment by terasum** [comment]
@Hunlongyu @shawkynasr 非常感谢建议，UI这方面我确实美感不足，只能按照现在的有道的UI仿了一个，我最近联系了一个设计师朋友会帮我设计一些界面, 希望能够更加清爽一些

**Comment by terasum** [comment]
@shawkynasr UI 已经作调整，请下载 v2.0.3 之后版本体验
