### ISSUE TITLE
[bug] 软件右上4个选项图标无法展示 (windows)

### ISSUE THREAD

**Issue by Hunlongyu** [terasum/medict#121]
![image](https://user-images.githubusercontent.com/15273630/128650429-37e28356-857d-4578-9429-8d75e4a7a73b.png)
![image](https://user-images.githubusercontent.com/15273630/128650444-6d288664-7900-4181-8bfc-8201b3411736.png)

**Comment by terasum** [comment]
@Hunlongyu 需要先添加一下词典的，下载一个 mdx/mdd 词典然后在设置中配置一下就可以使用了，词典可以到这个论坛下载
https://forum.freemdict.com/

**Comment by terasum** [comment]
@Hunlongyu 我看你上面的几个选项都没有出来，先尝试把软件拉宽一些，就可以看到选项，这是样式更新后出现的问题，我稍后会修复

**Comment by terasum** [comment]
@Hunlongyu v2.0.4 已经修复
