### ISSUE TITLE
versoin3.x macos 版本以及启动问题

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [terasum/medict#634]
能做个mac上版本3的安装包（dmg或pkg）么，Source code无法安装呀

**Comment by terasum** [comment]
我正在处理打包的问题，稍晚就会打包出来

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    期待中，坐等，快两年了，总算更新了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Chen ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月15日 21:52
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [terasum/medict] 能做个mac上版本3的安装包（dmg或pkg）么，Source code无法安装呀 (Issue #634)
        
      
    
  
  
我正在处理打包的问题，稍晚就会打包出来

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by shoudeyunkaijianyueming** [comment]
老哥，安装包还要多久，好期待

**Comment by terasum** [comment]
@shoudeyunkaijianyueming  https://github.com/terasum/medict/releases/tag/v-3.0.1-alpha-5a37d1 试试

**Comment by terasum** [comment]
@shoudeyunkaijianyueming  这个版本需要在 $HOME 目录下新建配置文件夹 `.medict`
/Users/yourname/.medict
```
├── dicts
│   ├── OALE8
│   │   ├── jquery.js
│   │   ├── oale8.mdd
│   │   ├── oale8.mdx
│   │   ├── oalecd8e.css
│   │   ├── oalecd8e.js
│   │   └── us_pron.png
│   └── ODE_3e
│       ├── ODE.css
│       ├── Oxford Dictionary of English 3e.jpg
│       ├── Oxford Dictionary of English 3e.mdd
│       └── Oxford Dictionary of English 3e.mdx
└── medict.toml
```

**Comment by terasum** [comment]
/Users/yourname/.medict/medict.toml 的内容:

```
BaseDictDir="$HOME/.medict/dicts"
StaticServerPort=9183
```

**Comment by shoudeyunkaijianyueming** [comment]
直接闪退，放入词典闪退，不放词典不闪退

**Comment by terasum** [comment]
@shoudeyunkaijianyueming 能否使用 Terminal 运行这个命令；
```
/Applications/Medict.app/Contents/MacOS/Medict
```

P.S. 可以 `Control-C` 退出

把控制台的输出信息粘贴一下，我看下什么问题

**Comment by shoudeyunkaijianyueming** [comment]
控制台输出信心没看到这个软件呀，该复制哪项

**Comment by shoudeyunkaijianyueming** [comment]
<img width="170" alt="image" src="https://github.com/terasum/medict/assets/71814666/1c4f8826-6610-435d-b62c-86d87abffa35">

**Comment by shoudeyunkaijianyueming** [comment]
Last login: Sat Sep 16 15:27:43 on ttys000
lei@shileideMacBook-Pro ~ % /Applications/Medict.app/Contents/MacOS/Medict
panic: open : no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
	/Users/runner/work/medict/medict/main.go:51 +0x53d
lei@shileideMacBook-Pro ~ % 

终端是这样的

**Comment by shoudeyunkaijianyueming** [comment]
我的默认medict.toml是这个BaseDictDir="$HOME/.medict/dicts"
StaticServerPort=1234
APIServerPort=8080
我改成你给我那个了

**Comment by shoudeyunkaijianyueming** [comment]
无论是那种都闪退了，控制台里面还没有这个软件

**Comment by terasum** [comment]
我看了一下你的输出，应该是文件路径不对，应用路径是存在的，没有找到配置文件

| |
ChenQuan
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月16日 15:34 |
| 收件人 | terasum/medict ***@***.***> |
| 抄送人 | Chen ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [terasum/medict] 能做个mac上版本3的安装包（dmg或pkg）么，Source code无法安装呀 (Issue #634) |

无论是那种都闪退了，控制台里面还没有这个软件

**Comment by shoudeyunkaijianyueming** [comment]
那我该改哪里，请您指导一下

**Comment by shoudeyunkaijianyueming** [comment]
我的配置文件是按照您提供的改的呀

**Comment by terasum** [comment]
您打开 Terminal ，输入以下命令

ls $HOME/.medict
如果说文件夹不存在，则输入
mkdir -p $HOME/.medict

cd $HOME/.medict && open -a Finder .
在打开的文件夹中进行配置文件管理，里面应该有 medict.toml

| |
ChenQuan
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月16日 16:21 |
| 收件人 | terasum/medict ***@***.***> |
| 抄送人 | Chen ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [terasum/medict] 能做个mac上版本3的安装包（dmg或pkg）么，Source code无法安装呀 (Issue #634) |

那我该改哪里，请您指导一下

**Comment by terasum** [comment]
@shoudeyunkaijianyueming 你好，白天不方便处理，您可以按照如下步骤解决问题：
1. 打开 `终端.app` , 输入如下命令
```
mkdir -p $HOME/.medict/dicts
```
2. 然后输入如下命令
```
cd $HOME/.medict && open -a Finder .
```
<img width="742" alt="image" src="https://github.com/terasum/medict/assets/20042193/9bae41b0-8d1b-4622-a0a5-cbfd6711658f">

3. 打开 Finder 之后，可以看到如下文件夹
<img width="932" alt="image" src="https://github.com/terasum/medict/assets/20042193/b5bc1dd4-00af-4d63-8c37-c769709f90cb">

4. 在这个文件夹中，可以看到 `medict.toml` 配置文件，可以编辑这个配置文件，内容如下:
```
BaseDictDir="$HOME/.medict/dicts"
StaticServerPort=9183
```
<img width="967" alt="image" src="https://github.com/terasum/medict/assets/20042193/c1563070-cb28-4dcb-b842-11994ae0f80e">

5. 您可以将您的词典放到 `dicts` 文件夹中，类似我这个方式：
<img width="932" alt="image" src="https://github.com/terasum/medict/assets/20042193/038a912a-174f-408f-a747-579c1f970c04">

如果还有问题您可以随时告知，晚上我有时间跟进解决的。

**Comment by shoudeyunkaijianyueming** [comment]
`您将安装包撤掉了，而我也降级到旧版本了，新版本的问题，绝不是按照您说的步骤就可以解决的，相反我认为我之前的操作没有问题，我是等待新版本稳定吧，谢谢您了`

**Comment by terasum** [comment]
@shoudeyunkaijianyueming 好的，安装包撤掉是因为我一直在测试 github action，有很多版本被打包出来，所以我删掉了一些版本，您可以再等两天，我把配置文件的配置放到界面上来。

另外从
```
panic: open : no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
/Users/runner/work/medict/medict/main.go:51 +0x53d
```
的错误上看，应该是无法找到词典文件导致的，也有可能是mac文件访问权限的问题，这几个问题我会一并解决，请您再耐心等待几天。

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    没事，本来您就是免费开发的，您不用这么客气
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Chen ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月16日 21:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [terasum/medict] 能做个mac上版本3的安装包（dmg或pkg）么，Source code无法安装呀 (Issue #634)
        
      
    
  
  
@shoudeyunkaijianyueming 好的，安装包撤掉是因为我一直在测试 github action，有很多版本被打包出来，所以我删掉了一些版本，您可以再等两天，我把配置文件的配置放到界面上来。
另外从
panic: open : no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
/Users/runner/work/medict/medict/main.go:51 +0x53d

的错误上看，应该是无法找到词典文件导致的，也有可能是mac文件访问权限的问题，这几个问题我会一并解决，请您再耐心等待几天。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by terasum** [comment]
@shoudeyunkaijianyueming 你好，你遇到的问题我进行了一些代码上的修复，如果有空的话可以试试这个版本：

https://github.com/terasum/medict/releases/tag/v-3.0.1-alpha-abf638

**Comment by shoudeyunkaijianyueming** [comment]
Error

Istat : no such file or directory
仍然错误

**Comment by shoudeyunkaijianyueming** [comment]
<img width="978" alt="图片" src="https://github.com/terasum/medict/assets/71814666/7656ef05-d050-49ef-97da-53a378eb0f1d">

**Comment by terasum** [comment]
@shoudeyunkaijianyueming  请问可以把 dicts 内部的各个词典展开我看看吗？我的词典树是这样的：
<img width="981" alt="image" src="https://github.com/terasum/medict/assets/20042193/7b45e085-caa3-469d-9bb7-754fcaeab1f0">

**Comment by shoudeyunkaijianyueming** [comment]
<img width="647" alt="图片" src="https://github.com/terasum/medict/assets/71814666/8254528b-8936-4ca4-8d69-1f11f66a7e2c">

**Comment by terasum** [comment]
我按照你的目录结构测试了一下，词典目录是没有问题的，目前看应该是默认生成配置文件的问题：
麻烦尝试修改 `/Users/yourname/.medict/medict.toml `, 内容修改为:
```
BaseDictDir="$HOME/dicts"
```
仅有上面一行内容，然后保存，切记是 `BaseDictDir` 原来代码里面写的是 `baseDictDir` 所以可能是配置错误读取不到
另外原来的配置是 `$HOME/.medict/dicts` 现在修改为了 `$HOME/dicts`

然后下载这个版本麻烦再试试，我新增了一些新的代码防御和错误提示：
https://github.com/terasum/medict/releases/tag/v-3.0.1-alpha-ba0afd

@shoudeyunkaijianyueming

**Comment by terasum** [comment]
@shoudeyunkaijianyueming 另外，在首次安装的app中，默认写入的模板也存在一些问题，默认写入的是：

```
DictBaseDir="$HOME/.medict/dicts"
```
这是错误的，正确的应该是：

```
BaseDictDir="$HOME/dicts"
```
上面的最新版本还未修复默认写入模板的问题，您可以按照我说的将配置文件修改为如下内容:
`/Users/yourname/.medict/medict.toml ` :

```
BaseDictDir="$HOME/dicts"
```

然后将词典放入  `/Users/yourname/.medict/dicts` 即可。

**Comment by shoudeyunkaijianyueming** [comment]
到底是BaseDictDir="$HOME/dicts"还是DictBaseDir="$HOME/dicts"默认产生的是DictBaseDir="$HOME/dicts"

**Comment by shoudeyunkaijianyueming** [comment]
是需要改成BaseDictDir="$HOME/dicts"么

**Comment by shoudeyunkaijianyueming** [comment]
1. <img width="383" alt="图片" src="https://github.com/terasum/medict/assets/71814666/eb6b1ca0-ce53-40b7-b739-39543b894d5f">

**这样并不闪退，但是应该保留哪个**，同时

2. <img width="169" alt="图片" src="https://github.com/terasum/medict/assets/71814666/e0d72f72-8663-4187-ad9c-59b94c821bc2">

词典并没有图标，当然其他设置键也是不可用，
不过一大进步，感谢

**Comment by terasum** [comment]
@shoudeyunkaijianyueming  `BaseDictDir="$HOME/dicts"` 是正确的。

词典图标目前只认识 `cover.png` 或者 `cover.jpg` ，可以在词典mdx所在文件夹，放一个 `cover.jpg` 或 `cover.png`

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，感谢，但是可能目前我还是会使用旧版，想在等等，等稳定了吧，毕竟新版测试后再下旧版需要重配置
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Chen ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月19日 21:52
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [terasum/medict] versoin3.x macos 版本以及启动问题 (Issue #634)
        
      
    
  
  
@shoudeyunkaijianyueming  BaseDictDir="$HOME/dicts" 是正确的。
词典图标目前只认识 cover.png 或者 cover.jpg ，可以在词典mdx所在文件夹，放一个 cover.jpg 或 cover.png

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by terasum** [comment]
嗯嗯，非常感谢您的支持，版本稳定之后会第一时间通知您试用，非常感谢！

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    大佬别这么客气，非常感谢您的无偿开发！！！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Chen ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月19日 22:50
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [terasum/medict] versoin3.x macos 版本以及启动问题 (Issue #634)
        
      
    
  
  
嗯嗯，非常感谢您的支持，版本稳定之后会第一时间通知您试用，非常感谢！

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
