### ISSUE TITLE
最新版的词典mdx, mdd文件放在哪才能被最新版的软件识别

### ISSUE THREAD

**Issue by likaigelikaige** [terasum/medict#635]
RT，点击右上角的词典和设置按钮没反应

**Comment by terasum** [comment]
@likaigelikaige 那两个功能还在开发过程当中...
如果您是 macos 系统，您可以按照如下操作进行：
打开 Finder ，然后按住 `Control-Shift-G`:
<img width="932" alt="image" src="https://github.com/terasum/medict/assets/20042193/5a5636f8-cc63-44a7-b1e8-44f5d12bb87d">

<img width="472" alt="image" src="https://github.com/terasum/medict/assets/20042193/6462a4f1-790c-4e18-97c2-c4bfe35f3eef">

输入文件地址: `/Users/yourusername/.medict` 
(其中 `yourusername` 改成你自己的用户名)

词典放在 dicts 中，按照如下方式组织：
<img width="932" alt="image" src="https://github.com/terasum/medict/assets/20042193/2d8d2a17-e95c-4835-b093-9475b5a2adf3">

一个文件夹一个词典：
<img width="932" alt="image" src="https://github.com/terasum/medict/assets/20042193/af2823cd-bdbb-45a5-8882-f16c198bade3">


配置文件为  `medict.toml`，内容为:
```
BaseDictDir="$HOME/dicts"
```

**Comment by terasum** [comment]
另外词典功能预计今天能够开发完成

**Comment by likaigelikaige** [comment]
非常感谢！

**Comment by terasum** [comment]
另外，词典封面需要命名为  `cover.png` 或 `cover.jpg` 目前因为比较粗糙，仅能够识别这两个文件
