### ISSUE TITLE
[bug] 无法加载mdd文件中的 css

### ISSUE THREAD

**Issue by shawkynasr** [terasum/medict#66]
无法加载mdd里面css

**Comment by terasum** [comment]
@shawkynasr 目前我测试下来，CSS文件主要以外挂为主，内嵌的CSS词典目前还没有测试过，是否能够提供一个测试样例词典呢？

**Comment by terasum** [comment]
@shawkynasr 你好，现在Develop分支已经支持查词界面调试资源了
![image](https://user-images.githubusercontent.com/20042193/126726093-6fb1496d-ecc8-4df3-877b-8975f0fe7c45.png)

如果资源存在，则contentSize不为零

![image](https://user-images.githubusercontent.com/20042193/126726148-f261ce48-3bbb-4b63-8476-ca5e8669549b.png)

**Comment by shawkynasr** [comment]
解决了，谢谢

**Comment by shawkynasr** [comment]
还没解决，有一些词典mdd看不到css

**Comment by terasum** [comment]
@shawkynasr 能否提供一下 “一些词典” 的原始mdx文件呢？方便我调试一下，感谢支持！

**Comment by terasum** [comment]
大部分情况已经解决，如果有问题请重开issue

**Comment by terasum** [comment]
@shawkynasr thank you for reporting, and I'll fix this

**Comment by terasum** [comment]
已经支持
